version: '3.6'

x-common-config: &common-config
  restart: unless-stopped

x-airflow-template: &airflow-template
  <<: *common-config
  image: apache/airflow:2.0.0-python3.8
  volumes:
    - ${DAGS_FOLDER}:/opt/airflow/dags
  environment:
    - AIRFLOW__CORE__FERNET_KEY
    - AIRFLOW__CORE__DEFAULT_TIMEZONE
    - AIRFLOW__CORE__EXECUTOR
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
    - AIRFLOW__CORE__DAGS_FOLDER
    - AIRFLOW__CORE__LOAD_EXAMPLES
    - AIRFLOW__CORE__PARALLELISM
    - AIRFLOW__CORE__DAG_CONCURRENCY
    - AIRFLOW__CORE__MAX_ACTIVE_RUNS
    - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
    - AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE
    - AIRFLOW__LOGGING__REMOTE_LOGGING
    - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    - AIRFLOW__WEBSERVER__NAVBAR_COLOR
    - AIRFLOW__WEBSERVER__DEFAULT_DAG_RUN_DISPLAY_NUMBER
    - AIRFLOW__CELERY__BROKER_URL
    - AIRFLOW__CELERY__WORKER_AUTOSCALE
    - AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS
    - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN
    - AIRFLOW__CELERY__RESULT_BACKEND
    - AIRFLOW__WEBSERVER__FILTER_BY_OWNER
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB


services:
  redis:
    <<: *common-config
    image: redis:5.0.8-alpine
    healthcheck:
      test: redis-cli ping

  database:
    <<: *common-config
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  

  webserver:
    <<: *airflow-template
    depends_on:
      - database
    command: webserver
    ports:
      - ${AIRFLOW_PORT}:8080
    healthcheck:
      test: curl --fail-early --fail http://webserver:${AIRFLOW_PORT}/health
      start_period: 2m

  scheduler:
    <<: *airflow-template
    depends_on:
      - database
      - redis
    command: scheduler

  worker:
    <<: *airflow-template
    depends_on:
      - scheduler
    command: celery worker

  flower:
    <<: *airflow-template
    depends_on:
      - scheduler
    command: celery flower
    ports:
      - ${FLOWER_PORT}:5555


# Needed to persist the Postgres data in Windows
volumes:
  pgdata: 
    driver: local
